# Site
name: 'Producement'
description: 'Customer-centric product engineering. The best products result from understanding the needs of the people who will use them.'
meta_description: 'Customer-centric product engineering. The best products result from understanding the needs of the people who will use them.'
logo: 'assets/images/bull.svg'
favicon: 'assets/images/favicon.ico'
about: 'https://producement.com'
baseurl: ''
google_analytics: 'UA-104411241-2'
disqus: 'producement'
mailchimp-list: 'https://producement.us19.list-manage.com/subscribe/post?u=5b6ada05b4d593bd193222bd0&amp;id=50b519fd01'

# Authors
authors:
  maido:
    name: Maido
    display_name: Maido
    gravatar: 11714de68faa827e62c4129eee1f147d
    email: maido@producement.com
    web: https://producement.com
    twitter: https://twitter.com/v3rm0n
    description: 'Co-founder and Product Engineer at Producement'
  erko:
    name: Erko
    display_name: Erko
    gravatar: a695d089200e50b03898662a948bf4b8
    email: erko@producement.com
    web: https://producement.com
    #twitter: https://twitter.com/wowthemesnet
    description: 'Co-founder and Product Engineer at Producement'
  jordan:
    name: Jordan
    display_name: Jordan
    gravatar: 1ffc3433e1ab9bd3d4acf6317b2d3913
    email: jordan@producement.com
    web: https://producement.com
    #twitter: https://twitter.com/wowthemesnet
    description: 'Co-founder and Product Engineer at Producement'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
